<script>
    // Generated by CoffeeScript 2.1.0
(function() {
    $(function() {
        // $.growl({
        //     title: "Growl",
        //     message: "Hi I'm Sash"
        // });

        @if (Session::has('error_message'))
            // event.preventDefault();
            // event.stopPropagation();
            return $.growl.error({
                message: "{{ Session::get('error_message') }}"
            });
        @endif

        @if (Session::has('error1'))
            // event.preventDefault();
            // event.stopPropagation();
           
            return $.growl.error1({
                message: "{{ Session::get('error1') }}"
            });
        @endif

        @if (Session::has('notice'))
            // $('.notice').s(function(event) {
            //     event.preventDefault();
            //     event.stopPropagation();
                return $.growl.notice({
                    position: center
                    message: "{{ Session::get('notice') }}"
                });
            // });
        @endif

        $('.warning').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.warning({
                message: "read all details carefully"
            });
        });

        $('.notice1').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.notice1({
                message: "You have 4 notification"
            });
        });
        return $('.warning1').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.warning1({
                message: "read all details carefully"
            });
        });
    });
}).call(this);



@if (Session::has('notice_message'))
    // function not2() {
        notif({
            msg: "{{ Session::get('notice_message') }}",
            type: "info",
            width:300,
            opacity: 0.8,
            position: "center"
        });
    // }
@endif

</script>