name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.LARAVEL_SITE_SERVER }}
        username: ${{ secrets.LARAVEL_SITE_USER }}
        password: ${{ secrets.LARAVEL_SITE_PASS }}
        debug: true  # Enable detailed logging
        timeout: 60000  # Increase timeout value to 60000ms (60 seconds)

    - name: ssh key passphrase
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          whoami
          ls -al
          cd tourismafrikanianig.com
          composer install --ignore-platform-reqs
          php artisan storage:link
